### ISSUE TITLE
Suggestion: use patsy

### ISSUE THREAD

**Issue by alexpghayes** [dmsul/econtools#3]
It makes model specification nicer.

https://patsy.readthedocs.io/en/latest/quickstart.html

**Comment by dmsul** [comment]
Hi @alexpghayes, thanks for your interest in `econtools`! While we might do patsy integration at some point in the future, it's not a priority right now because you can use patsy directly to create your interaction variables, etc., and then pass that DataFrame to `econtools.metrics.reg`.
